from typing import overload

class ServerSHM:
    def __init__(self, port_number: int, bus_count: int) -> None: ...
    def describe_scope_buffer(self, index: int) -> tuple[int, int]: ...
    def read_scope_buffer(self, index: int) -> tuple[int, list[float]]: ...
    @overload
    def __getitem__(self, item: int) -> float: ...
    @overload
    def __getitem__(self, item: slice) -> list[float]: ...
    @overload
    def __setitem__(self, item: int, value: float) -> None: ...
    @overload
    def __setitem__(self, item: slice, value: list[float]) -> None: ...
